Kpenny pact contract (#72)
* kpenny contract draft

* kpenny with basic repl tests

* delete kpenny outside the folder

* change redeem to one time redemption for admin

* delete pact history

* add fungible-test

* add a failing case of redeem-all

* add deadline to transfer-create

* fix env-chain-data date to fix repl error

* convert -> reserve, add RESERVE event

* move deadline to TRANSFER cap

* change redeem to custom redeem

* add yaml file

* change sender in kpenny.yaml

* install transfer cap in contract

* add deadline test for kpenny

* add test to redeem to different account

Co-authored-by: fmelp <melpignanof@gmail.com>
Co-authored-by: ggobugi27 <ggobugi27@github.com>

diff --git a/.github/workflows/pact.yml b/.github/workflows/pact.yml
--- a/.github/workflows/pact.yml
+++ b/.github/workflows/pact.yml
@@ -2,10 +2,10 @@
 
 name: CI
 
-# Controls when the action will run. 
+# Controls when the action will run.
 on:
   push:
-    branches: 
+    branches:
       - master
   pull_request:
 
@@ -23,7 +23,7 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-        
+
       - name: Get pact binary
         run: |
           mkdir bin
@@ -42,6 +42,12 @@ jobs:
       - name: pact/test/test.repl
         run: |
           bin/pact -t pact/test/test.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: pact/kpenny/kpenny.repl
+        run: |
+          bin/pact -t pact/kpenny/kpenny.repl > out.log 2>&1
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
